### ISSUE TITLE
wrong mime type for script files served from coriolis.edcd.io

### ISSUE THREAD

**Issue by cmdr-maeggle** [EDCD/coriolis-build#1]
Currently the server for coriolis.edcd.io serves Javascript files with the wrong mime type, which may cause issues with some browser security policies and plugins like NoScript.

HTML source fragment in https://coriolis.edcd.io/:

```
<script src="/app.bb87cc.js" charset="utf-8" crossorigin="anonymous"></script>
```

Request:

```
GET /app.bb87cc.js HTTP/1.1
Host: coriolis.edcd.io
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://coriolis.edcd.io/
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

Response:

```
Date: Sun, 05 Feb 2017 11:49:45 GMT
Server: Apache
Last-Modified: Fri, 03 Feb 2017 22:30:06 GMT
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: sameorigin
X-XSS-Protection: 1; mode=block
x-ua-compatible: IE=edge
Content-Length: 904
Keep-Alive: timeout=15, max=500
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

Per .htaccess file in the project trunk the appropriate Content-Type in the response should be rewritten to `text/javascript`, but isn't. I think this should be fixed on the server side, but a workaround could be to embed scripts in the HTML source with an explicit attribute `type="text/javascript`.

**Comment by themroc5** [comment]
I can not confirm your Response. I get `application/javascript` as `Content-Type`.
See https://securityheaders.io/?q=https%3A%2F%2Fcoriolis.edcd.io%2Fapp.e9ca9e.js&followRedirects=on

**Comment by cmdr-maeggle** [comment]
I can reproduce that for the resource that you used:

```
$ curl -I 'https://coriolis.edcd.io/app.e9ca9e.js' -H 'Host: coriolis.edcd.io' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0' -H 'Accept: */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://coriolis.edcd.io/' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0'
HTTP/1.1 200 OK
Date: Sun, 05 Feb 2017 12:32:10 GMT
Server: Apache
Last-Modified: Fri, 03 Feb 2017 22:30:06 GMT
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
Keep-Alive: timeout=15, max=500
Connection: Keep-Alive
Content-Type: application/javascript; charset=utf-8
```

Interestingly the response for the resource that is linked in the response that I get is different:
```
curl -I 'https://coriolis.edcd.io/app.bb87cc.js' -H 'Host: coriolis.edcd.io' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0' -H 'Accept: */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://coriolis.edcd.io/' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0'
HTTP/1.1 200 OK
Date: Sun, 05 Feb 2017 12:31:13 GMT
Server: Apache
Last-Modified: Fri, 03 Feb 2017 22:30:06 GMT
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
X-UA-Compatible: IE=edge
Content-Length: 904
Keep-Alive: timeout=15, max=500
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

Note the different content types. Request headers are the same for both requests.
I checked from both my current WAN and a remote server.

HTML source contains the following Coriolis version info:

```
window.CORIOLIS_VERSION = '2.2.3';
window.CORIOLIS_DATE = '2016-11-24';
```

**Comment by themroc5** [comment]
Because that file doesnt exist anymore. Try to open in your browser :)
That makes me wonder - why does it not throw a 404?

**Comment by cmdr-maeggle** [comment]
I cleared my browser caches and local storage a few times to make sure that it's not a rogue file... Tunneled the request through another server and, sure enough, got a different response (`window.CORIOLIS_VERSION = '2.2.13';`). Seems to be an issue with the ISP that I am using atm.

Sorry for the confusion. 404 or another error response code would be welcome, but are not the root issue here.
